GOOGLE_SHEETS_CREDENTIALS = '''
{
  "type": "service_account",
  "project_id": "controlearquivosprojeta",
  "private_key_id": "9e4e33de1ac94ff17189ecc7a48985cc39e4443d",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCLnF4Nz+mUvtVI\n59/9Zc66A1MUJH4aJOZtmxMbUwXg1wFWBxYhzSfYYKpG/fIAgHPUT2IuUN9k/+Dk\neTaSxVINWsN8dxbSVPX21FA9PhZzJhN/HAdAGvtO6CyJi6s1gZ7yXXQzANCrIjjX\nmidYxrhriYLTQQXqeYHEMSGBEN0GF6K1GSWKmgWfVtPsJ8qxCcwPRLEbMzs+NDw0\nohwrxnjvjtdS3HsgQFya2RPgjESirBCL553hCNNlcrd7KUm4Yv5MW9VdBBzfZrkO\nhMXsSFXASBOW6yTZH/pgmR+8nbmz0etmGJADtrIDzjDIrrRXATUlhILhaTqNr4Xj\nAYJ69qk3AgMBAAECggEABBMC6FQ3RvWgv3tLg7ELNW/BEUpRE+vHBmjV6gKXawZi\nvOVWpZNqXiquakEYww7JZ+dBTSaoC6Y34E/XRHDrIh+jVbLoJSjFHPPoGY7GMnsT\nJshyDIWllyJroPuRtgbuzJX3zg1fEh3c2t6zcKhN147lv5fKBpM5zGu197KUMCX7\n/xz7PT7yE8y/XtqIi/U82alLZqkYTBAIq5ylE7/qGHl1krg2JMHZ57A9Y5DB+aPx\nLcpsvAofcsHKSOVZqGChGNULSL3WzDpkwbnT2zNGrNekCKe9pI1SPGOcmB//okDO\nceO7gyVVCN5Cpq0iQebucKiyNmJx4Xm9ovAxgucS2QKBgQC/82q5I8q8X6rkuky6\nn/5YqC1+5d4a3XrqI4vv/n7whTtEXl0+VSlwDptgK/553OVb0DZJ+A4KL8odiwPb\nv7EyKzxz4AvmuFMn6ycMrd/2dkXzHIdD/u0X9oE/Bwhr0/QnpGasqvctKA/G60vP\nmY4dQ+VhMkBocWaJZeUBZ6rdzwKBgQC6MgahCYxm4JtfOU+LdymDQ6UrJ+mHZUnf\nEZolrmzLqM0PbSuzgYenhQ05Vmaik8MyTchAz02+jH3rXcU5Kc+UC9kbR84bAep7\nI6dcuMwXJ26su5RJydersczTMb6wDDOReBjvh7KBuwyLaFSn93U3RC9ejtp5ILHi\nVkE0QQkAGQKBgQCTwPyivMFfFUkHvbw4X9W6SuKSbsDz7w6hUnFycHUoEXZYn0ap\nJ4a5IhVKBzNgfL/0V6aic5XjE3xCF3MF4V21n4BuNcUTeUlRTfqGEQV3wvz/MTOS\nDJZWvsIoUPKThdjH9w2t1gBkOxVB6nc1ux6gulXD5pmbi8cA9nU8Cp+FEwKBgQCX\nmMl67hpJXNBD7JaON7wt6rKc+4cQvPAzVdKKoYRlIQ+sYrd1FJ5NT3Af4e/4qJQB\n7gCAfAiRfzO6oYNFcnxWznq60nDF3n56OeI3BSLuKyXaL3OhzFvzp/TbcyINljGa\nXAz5YSN+qrug+ZYLl9fw4mwq8eaBPpR2csHt+JGKaQKBgQCJOWDV2pli7yQgGFJm\nOTELxaFRtag6Td5tEmXZ/ivPph+A8MH8FKbWABj8y/uKsCCLEL0TABHVyOjN2Rqh\nyyNPRLQQvhkK/dH/AY8Eno3wOO5RXUWbXcA4oNfQ4DfhzZMDWnn6AN5brjEZDEI1\n9CTePFPHM7NBoLS3V1xaaWjKHw==\n-----END PRIVATE KEY-----\n",
  "client_email": "controlearquivosprojeta@controlearquivosprojeta.iam.gserviceaccount.com",
  "client_id": "105622413582144227741",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/controlearquivosprojeta%40controlearquivosprojeta.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}'''

[usuarios.Liderancas]
perfil = "Liderancas"
senha = "PRJ@2025"


[usuarios.Tecnicos]
perfil = "Tecnicos"
senha = "PRJ@2025"
